sudo: required
language: java
dist: trusty
matrix:
  include:
  - env:
    - TESTS=true
    - COVERAGE=true
  - env:
    - CROSSDOCK=true
services:
- docker
env:
  global:
  - DOCKER_VERSION=1.11.1-0~trusty
  - DOCKER_COMPOSE_VERSION=1.7.0
  - COMMIT=${TRAVIS_COMMIT::8}
  # travis encrypt -r <repo> SONATYPE_USER=<username>
  - secure: "ZooX2qR0QYbUisOFyZctgKnG4eviI7/c9nx0qbUyYX9ZuG5gduxASR6awIlLnd5sqVJeZFCpUeMN79raE0iWAD62WqD4WNVfdE5iAHmuAsYlXAmQKnWQkuiW2PaeA6n45yQ4Ma+AnotjogyEMx3vLBnJEfedlPNhm/kcsqu/XSaobT7mHomJOcBDKmY99vcl/0xCPPsTHsRzUsyCjXkSvm46ZnSut13jUBvuS/a6P0slQggtgYmflI+lFQmitx/HgUliN4s6NdtL3E3CU5Bri7qOV5la8i5P8wuTFn/PS/AqQ7s7VDhFMA4EQR++/NoNm59/evCTYUKrYJ9kHyRHFulY1lrYNMhewld/S72rHS3AMu6c+mXWb9rrLrlmZeUiLLzy9XMm2vxIu/m7FqM7/2lkKGfs8Mb58zb3EGf3PQkthpthqvuA+avDIr6esY6f959PqhRg7IDEeKYKj0zeZxwFoQ/9pMNp4H5UDo1L+7qwT3TJPcUgJqHUVYLFpGzZJEvK9ivnvQ+suTrYvmMzS3YV8n6xltJzVWBSfjtmzmAMf1ygv8AsMqFFZ1Sv7tlz2Jxl1JbsddfLnDsmmQssh1hP6YCa4Q/6f5XRjiln8Xdft1zcMZG4xdlR8G8d1kIIYJU6FZBSiK68gycybwm7gkWdjeyEhV5wyrQ/VGfecSo="
  # travis encrypt -r <repo> SONATYPE_PASSWORD=<password>
  - secure: "o66kcCAwpDjkmQgCi/dwKpylhXC4i8OdQvpa45egl0kuDwEibm5aETQ0fDnKCXwQMhb6gYpO2cgq9Cd0n38voYM63uKn4CVsc/bLmlRwTkowKZVaVLGmTYaqpk3G8fMrq8OMUCcHGlPCnxXyvr2kALhsspsO9WpVm/3gQjNEM4vG5VudWmnn/Vt7tTvEZslIJgkW2UEZSd8bWm2KLCgrjsKUyqJMH/rqlXGHV14vQA2yJpCsOGqz9DoFYgSRDxyhWlJpMe/mqyoPFOxpt1B9OejKQFXQanaEoZklonevzfpYCkG9XskW3NFBkCM6RP4xA9icOKisGvT6IW3zq457TY15pcd4gVfBfotF0h1jaf9VNlV9DQ7ooCb/S/Kf5HGXiBexBFN8ScW+O02iq+uWpO5Bz1wkZY0gjcr1FzV68L70p1eCWA2JBjcPWgRt3H24oIqzaBg1ltyT8aAvKiu2/cpyd1+lYS9pHfHp/tmwezEY56+ZI9op4Zehuv5oKSrRPbL7OooYZNYIM7+VPGngMogtDSIppETmylkqpROFM/ISmT7ZBMD/58gcMigplhyH0EoTmurZCGE3ly5WMXsLUM3jguLRwDVgvx1XpCvDgHWtC7Q85b1aLPyB42q7ijCEzLqBqq1v/oImXpdrrKwrApPzavumaWtB5mcVJO2pLDc="
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- ./travis/prepare-signing.sh $encrypted_677f232983c0_key $encrypted_677f232983c0_iv
- if [ "$CROSSDOCK" == true ]; then bash ./travis/install-crossdock-deps.sh ; fi
script:
- if [ "$TESTS" == true ]; then make test-travis ; else echo 'skipping tests'; fi
- if [ "$COVERAGE" == true ]; then ./gradlew codeCoverageReport ; else echo 'skipping coverage'; fi
- if [ "$CROSSDOCK" == true ]; then bash ./travis/build-crossdock.sh ; else echo 'skipping crossdock'; fi
after_success:
- if [ "$COVERAGE" == true ]; then bash <(curl -s https://codecov.io/bash) ; fi
- if [ "$CROSSDOCK" == true -a "$TRAVIS_PULL_REQUEST" == false ]; then ./gradlew upload ; fi
